# Stages of the analysis, see DVC documentation

stages:
  test_iris:
    cmd: python -m analysis.test_iris.test_iris
    deps:
      - analysis/test_iris/test_iris.py
      - data/raw/test_iris/
    # no output data; autofilling values are already tracked by git
    # outs:
    #   - data/output/test_iris/
    #   - data/release/test_iris.tex
