channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - pip:
    # analysis
    - numpy
    - pandas[parquet]
    - plotly
    # development
    - dvc[gdrive]==3.56.0
    - ipykernel
    - black
    - nbconvert
    - jupyter_contrib_nbextensions
    - pre-commit
    - jupytext
  - r
  # analysis R
  - r-tidyverse
  - r-arrow
  - r-yaml
  # development R
  - r-IRkernel
  - r-languageserver
