channels:
  - conda-forge
  - nodefaults
dependencies:
  - python
  - pip
  - pip:
    # analysis
    - numpy
    - pandas[parquet]
    # development
    - ipykernel
    - black
    - nbconvert
    - jupyter_contrib_nbextensions
    - jupytext
