name: Sync LaTeX code with mirror repo

on:
  push:
    branches:
      - main

jobs:
  sync_latex:
    runs-on: ubuntu-latest
    env:
      LATEX_REPOSITORY: ${{ secrets.LATEX_REPOSITORY }}
      LATEX_TOKEN: ${{ secrets.LATEX_TOKEN }}

    steps:
      - name: 🚚 Checkout full repo
        uses: actions/checkout@v3
        with:
          path: "./full"
        if: ${{ env.LATEX_REPOSITORY != '' && env.LATEX_TOKEN != '' }}

      - name: 🚚 Checkout latex repo
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.LATEX_REPOSITORY }}
          token: ${{ secrets.LATEX_TOKEN }}
          path: "./latex"
        if: ${{ env.LATEX_REPOSITORY != '' && env.LATEX_TOKEN != '' }}

      - name: 🔄 Sync with latex repo
        run: |
          cd latex
          shopt -s extglob
          rm --recursive ./!(.git|.|..)
          shopt -u extglob
          shopt -s dotglob
          cp --recursive --dereference ../full/paper_slides/* .
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit --allow-empty -m "Update to `git -C ../full/ rev-parse --short HEAD`"
          git push
        if: ${{ env.LATEX_REPOSITORY != '' && env.LATEX_TOKEN != '' }}
